### ISSUE TITLE
是否少了一行traceMOVED_TASK_TO_OVERFLOW_DELAYED_LIST？

### ISSUE THREAD

**Issue by fefr** [QQxiaoming/gd32vf103_freertos#1]
`freertos/tasks.c`的[5075行](https://github.com/QQxiaoming/gd32vf103_freertos/blob/master/freertos/tasks.c#L5075)是不是需要插入`traceMOVED_TASK_TO_OVERFLOW_DELAYED_LIST();`？

我目前使用的SystemView版本是3.12

**Comment by QQxiaoming** [comment]
是的，这个位置确实漏掉了这一行，感谢您的提问
